services:
  mongodb:
    image: mongo:8.0
    container_name: gym-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gym_admin
      MONGO_INITDB_ROOT_PASSWORD: gym_secret
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
