# ConfigMap — спосіб зберігати конфігураційні дані в Kubernetes
# В нашому випадку — HTML-файл для вебсайту
apiVersion: v1 # Версія API Kubernetes
kind: ConfigMap # Тип ресурсу
metadata:
  name: website-content # Назва ConfigMap (будемо посилатись на неї)
data:
  index.html: | # Ключ = ім'я файлу, значення = вміст файлу
    <!DOCTYPE html>
    <html>
    <head>
      <title>RobotDreams EKS</title>
    </head>
    <body>
      <h1>Hello from EKS Cluster!</h1>
      <p>This is a static website running on Kubernetes (EKS)</p>
    </body>
    </html>
