---
# Це статичний inventory — просто список серверів з їх IP
# Аналогія: як contacts.json у frontend проєкті

all:
  children:
    # Група "webservers" — всі наші веб сервери
    webservers:
      hosts:
        ansible-web-1:
          ansible_host: 3.120.229.30   # IP першого сервера
        ansible-web-2:
          ansible_host: 3.120.131.139  # IP другого сервера
