---
# Змінні за замовчуванням для ролі baseline
# Їх можна перевизначити в group_vars або host_vars

# Публічний SSH ключ для деплою
# ВАЖЛИВО: це значення треба замінити на реальний ключ в group_vars!
deploy_ssh_public_key: ""
